using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentFinanceDetailManager : AgentFinanceDetailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AgentFinanceDetailManager(IAgentFinanceDetailRepository agentFinanceDetailRepository)
            : base(agentFinanceDetailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}