using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentVoucherTypeManager : AgentVoucherTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AgentVoucherTypeManager(IAgentVoucherTypeRepository agentVoucherTypeRepository)
            : base(agentVoucherTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}