using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentGroupTypeManager : AgentGroupTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AgentGroupTypeManager(IAgentGroupTypeRepository agentGroupTypeRepository)
            : base(agentGroupTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}