using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentFinanceDetail : AgentFinanceDetailBase
    {
        //<suite-custom-code-autogenerated>
        protected AgentFinanceDetail()
        {

        }

        public AgentFinanceDetail(decimal creditLimit, decimal outstandingBalance, decimal convertedBalance, decimal lastConversionRate, string? creditLimitCurrency = null, string? displayCurrency = null)
            : base(creditLimit, outstandingBalance, convertedBalance, lastConversionRate, creditLimitCurrency, displayCurrency)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}