using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentPermissionTypeManager : AgentPermissionTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public AgentPermissionTypeManager(IAgentPermissionTypeRepository agentPermissionTypeRepository)
            : base(agentPermissionTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}