using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentGroupType : AgentGroupTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected AgentGroupType()
        {

        }

        public AgentGroupType(string name, string? description = null)
            : base(name, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}