using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class PromoCodeUsageTrackingManager : PromoCodeUsageTrackingManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PromoCodeUsageTrackingManager(IPromoCodeUsageTrackingRepository promoCodeUsageTrackingRepository)
            : base(promoCodeUsageTrackingRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}