using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.CommonService.CommonServices
{
    public class PromoCodeMaster : PromoCodeMasterBase
    {
        //<suite-custom-code-autogenerated>
        protected PromoCodeMaster()
        {

        }

        public PromoCodeMaster(string name, decimal discountValue, DateTime dateEffectiveFrom, DateTime dateEffectiveTo, decimal minBookingAmount, int minNoOfNights, int minNoOfPax, int earlyBirdDays, DateTime validTimeFrom, DateTime validTimeTo, bool stackable, string? promoCode = null, string? serviceType = null, string? discountType = null, int? maxUsageLimit = null, int? maxUsagePerUser = null, string? customerType = null, string? paymentMethod = null, string? userGroup = null)
            : base(name, discountValue, dateEffectiveFrom, dateEffectiveTo, minBookingAmount, minNoOfNights, minNoOfPax, earlyBirdDays, validTimeFrom, validTimeTo, stackable, promoCode, serviceType, discountType, maxUsageLimit, maxUsagePerUser, customerType, paymentMethod, userGroup)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}