using TMSMS.CommonService.CommonServices;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.CommonService.CommonServices
{
    public class PromoCodeUsageTracking : PromoCodeUsageTrackingBase
    {
        //<suite-custom-code-autogenerated>
        protected PromoCodeUsageTracking()
        {

        }

        public PromoCodeUsageTracking(int? promoCodeMasterId, int userID, int bookingID, DateTime usageDate)
            : base(promoCodeMasterId, userID, bookingID, usageDate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}