using TMSMS.CommonService.CommonServices;
using TMSMS.CommonService.CommonServices;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class PromoCodeMasterManager : PromoCodeMasterManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PromoCodeMasterManager(IPromoCodeMasterRepository promoCodeMasterRepository,
        IRepository<Country, int> countryRepository,
        IRepository<City, int> cityRepository)
            : base(promoCodeMasterRepository, countryRepository, cityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}