using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class ProvinceManager : ProvinceManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ProvinceManager(IProvinceRepository provinceRepository)
            : base(provinceRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}