using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class RegionManager : RegionManagerBase
    {
        //<suite-custom-code-autogenerated>
        public RegionManager(IRegionRepository regionRepository)
            : base(regionRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}