using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class SupplierServiceTypeManager : SupplierServiceTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SupplierServiceTypeManager(ISupplierServiceTypeRepository supplierServiceTypeRepository)
            : base(supplierServiceTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}