using TMSMS.CommonService;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class SupplierMasterManager : SupplierMasterManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SupplierMasterManager(ISupplierMasterRepository supplierMasterRepository)
            : base(supplierMasterRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}