using TMSMS.CommonService.CommonServices;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.CommonService.CommonServices
{
    public class SupplierMaster : SupplierMasterBase
    {
        //<suite-custom-code-autogenerated>
        protected SupplierMaster()
        {

        }

        public SupplierMaster(int countryId, int supplierServiceTypeId, string name, string contactName, int supplierStatus, bool preffered, string? type = null, string? contactEmail = null, string? dialCode = null, string? contactPhone = null)
            : base(countryId, supplierServiceTypeId, name, contactName, supplierStatus, preffered, type, contactEmail, dialCode, contactPhone)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}