using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.CommonService.CommonServices
{
    public class WeekDayManager : WeekDayManagerBase
    {
        //<suite-custom-code-autogenerated>
        public WeekDayManager(IWeekDayRepository weekDayRepository)
            : base(weekDayRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}