using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.CommonService.CommonServices
{
    public class WeekDay : WeekDayBase
    {
        //<suite-custom-code-autogenerated>
        protected WeekDay()
        {

        }

        public WeekDay(string name, string dayAbbreviation, bool isWeekend, int displayOrder)
            : base(name, dayAbbreviation, isWeekend, displayOrder)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}