using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TMSMS.RestaurantService.Permissions;
using TMSMS.RestaurantService.RestaurantServices;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TMSMS.RestaurantService.Shared;

namespace TMSMS.RestaurantService.RestaurantServices
{
    public class RestaurantTypesAppService : RestaurantTypesAppServiceBase, IRestaurantTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public RestaurantTypesAppService(IRestaurantTypeRepository restaurantTypeRepository, RestaurantTypeManager restaurantTypeManager, IDistributedCache<RestaurantTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(restaurantTypeRepository, restaurantTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}