using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.RestaurantService.RestaurantServices
{
    public class RestaurantTypeManager : RestaurantTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public RestaurantTypeManager(IRestaurantTypeRepository restaurantTypeRepository)
            : base(restaurantTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}