using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.RestaurantService.RestaurantServices
{
    public class RestaurantTagManager : RestaurantTagManagerBase
    {
        //<suite-custom-code-autogenerated>
        public RestaurantTagManager(IRestaurantTagRepository restaurantTagRepository)
            : base(restaurantTagRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}