using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.RestaurantService.RestaurantServices
{
    public class RestaurantCuisineManager : RestaurantCuisineManagerBase
    {
        //<suite-custom-code-autogenerated>
        public RestaurantCuisineManager(IRestaurantCuisineRepository restaurantCuisineRepository)
            : base(restaurantCuisineRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}