using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.RestaurantService.RestaurantServices
{
    public class RestaurantDietaryTypeManager : RestaurantDietaryTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public RestaurantDietaryTypeManager(IRestaurantDietaryTypeRepository restaurantDietaryTypeRepository)
            : base(restaurantDietaryTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}