using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TMSMS.AgentService.Permissions;
using TMSMS.AgentService.AgentServices;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TMSMS.AgentService.Shared;

namespace TMSMS.AgentService.AgentServices
{
    public class AgentPermissionTypesAppService : AgentPermissionTypesAppServiceBase, IAgentPermissionTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public AgentPermissionTypesAppService(IAgentPermissionTypeRepository agentPermissionTypeRepository, AgentPermissionTypeManager agentPermissionTypeManager, IDistributedCache<AgentPermissionTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(agentPermissionTypeRepository, agentPermissionTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}