using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.VisaService.VisaServices
{
    public class VisaTypeManager : VisaTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VisaTypeManager(IVisaTypeRepository visaTypeRepository)
            : base(visaTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}