using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.VisaService.VisaServices
{
    public class VisaTermCategoryManager : VisaTermCategoryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VisaTermCategoryManager(IVisaTermCategoryRepository visaTermCategoryRepository)
            : base(visaTermCategoryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}