using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.VisaService.VisaServices
{
    public class VisaDiscountCategoryManager : VisaDiscountCategoryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VisaDiscountCategoryManager(IVisaDiscountCategoryRepository visaDiscountCategoryRepository)
            : base(visaDiscountCategoryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}