using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace TMSMS.VisaService.VisaServices
{
    public class VisaType : VisaTypeBase
    {
        //<suite-custom-code-autogenerated>
        protected VisaType()
        {

        }

        public VisaType(string name, string? subCategory = null, string? visaPurpose = null, string? description = null)
            : base(name, subCategory, visaPurpose, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}