using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TMSMS.VisaService.Permissions;
using TMSMS.VisaService.VisaServices;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TMSMS.VisaService.Shared;

namespace TMSMS.VisaService.VisaServices
{
    public class VisaTypesAppService : VisaTypesAppServiceBase, IVisaTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public VisaTypesAppService(IVisaTypeRepository visaTypeRepository, VisaTypeManager visaTypeManager, IDistributedCache<VisaTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(visaTypeRepository, visaTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}