apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        ports:
        - name: "http"
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /health-status
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        env:
        - name: "DOTNET_ENVIRONMENT"
          value: "{{ .Values.global.dotnetEnvironment }}"
        - name: "ElasticSearch__IsLoggingEnabled"
          value: "{{ .Values.global.elasticSearch.isLoggingEnabled }}"
        - name: "ElasticSearch__Url"
          value: "http://{{ .Release.Name }}-elasticsearch:{{ .Values.global.elasticSearch.port }}"
        - name: "Swagger__IsEnabled"
          value: "{{ .Values.swagger.isEnabled }}"
        - name: "AbpStudioClient__StudioUrl"
          value: "{{ .Values.global.abpStudioClient.studioUrl }}"
        - name: "AbpStudioClient__IsLinkEnabled"
          value: "{{ .Values.global.abpStudioClient.isLinkEnabled }}"
        - name: "App__CorsOrigins"
          value: "{{ include "tmsms.hosts.angular" . }}"
        - name: "App__HealthUiCheckUrl"
          value: "http://{{ .Release.Name }}-webgateway/health-status"
        - name: "ReverseProxy__Clusters__Agent__Destinations__Agent__Address"
          value: "http://{{ .Release.Name }}-agent"
        - name: "ReverseProxy__Clusters__Restaurant__Destinations__Restaurant__Address"
          value: "http://{{ .Release.Name }}-restaurant"
        - name: "ReverseProxy__Clusters__Visa__Destinations__Visa__Address"
          value: "http://{{ .Release.Name }}-visa"
        - name: "ReverseProxy__Clusters__Transfer__Destinations__Transfer__Address"
          value: "http://{{ .Release.Name }}-transfer"
        - name: "ReverseProxy__Clusters__Common__Destinations__Common__Address"
          value: "http://{{ .Release.Name }}-common"
        - name: "ReverseProxy__Clusters__Tour__Destinations__Tour__Address"
          value: "http://{{ .Release.Name }}-tour"
        - name: "ReverseProxy__Clusters__AuthServer__Destinations__AuthServer__Address"
          value: "http://{{ .Release.Name }}-authserver"
        - name: "ReverseProxy__Clusters__Administration__Destinations__Administration__Address"
          value: "http://{{ .Release.Name }}-administration"
        - name: "ReverseProxy__Clusters__Identity__Destinations__Identity__Address"
          value: "http://{{ .Release.Name }}-identity"
        - name: "ReverseProxy__Clusters__Saas__Destinations__Saas__Address"
          value: "http://{{ .Release.Name }}-saas"
        - name: "ReverseProxy__Clusters__AuditLogging__Destinations__AuditLogging__Address"
          value: "http://{{ .Release.Name }}-auditlogging"
        - name: "ReverseProxy__Clusters__Gdpr__Destinations__Gdpr__Address"
          value: "http://{{ .Release.Name }}-gdpr"
        - name: "ReverseProxy__Clusters__FileManagement__Destinations__FileManagement__Address"
          value: "http://{{ .Release.Name }}-fileManagement"
        - name: "ReverseProxy__Clusters__Language__Destinations__Language__Address"
          value: "http://{{ .Release.Name }}-language"
        - name: "ReverseProxy__Clusters__Chat__Destinations__Chat__Address"
          value: "http://{{ .Release.Name }}-chat"