global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'administration'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44321']
  - job_name: 'authserver'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44323']
  - job_name: 'identity'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44309']
  - job_name: 'gdpr'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44313' ]
  - job_name: 'filemanagement'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44361' ]
  - job_name: 'language'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44306' ]
  - job_name: 'saas'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44371' ]
  - job_name: 'chat'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44354' ]
  - job_name: 'auditlogging'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
      - targets: [ 'host.docker.internal:44314' ]
  - job_name: 'web'
    scheme: http
    metrics_path: 'metrics'
    static_configs:
    - targets: ['host.docker.internal:44385']