using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TMSMS.CommonService.Permissions;
using TMSMS.CommonService.CommonServices;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TMSMS.CommonService.Shared;

namespace TMSMS.CommonService.CommonServices
{
    public class ServiceTypesAppService : ServiceTypesAppServiceBase, IServiceTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public ServiceTypesAppService(IServiceTypeRepository serviceTypeRepository, ServiceTypeManager serviceTypeManager, IDistributedCache<ServiceTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(serviceTypeRepository, serviceTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}