using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TMSMS.CommonService.Permissions;
using TMSMS.CommonService.CommonServices;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TMSMS.CommonService.Shared;

namespace TMSMS.CommonService.CommonServices
{
    public class WeekDaysAppService : WeekDaysAppServiceBase, IWeekDaysAppService
    {
        //<suite-custom-code-autogenerated>
        public WeekDaysAppService(IWeekDayRepository weekDayRepository, WeekDayManager weekDayManager, IDistributedCache<WeekDayDownloadTokenCacheItem, string> downloadTokenCache)
            : base(weekDayRepository, weekDayManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}