using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace TMSMS.TransferService.TransferServices
{
    public class TransferTypeManager : TransferTypeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TransferTypeManager(ITransferTypeRepository transferTypeRepository)
            : base(transferTypeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}