using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using TMSMS.TransferService.Permissions;
using TMSMS.TransferService.TransferServices;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using TMSMS.TransferService.Shared;

namespace TMSMS.TransferService.TransferServices
{
    public class TransferTypesAppService : TransferTypesAppServiceBase, ITransferTypesAppService
    {
        //<suite-custom-code-autogenerated>
        public TransferTypesAppService(ITransferTypeRepository transferTypeRepository, TransferTypeManager transferTypeManager, IDistributedCache<TransferTypeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(transferTypeRepository, transferTypeManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}